version: 2.1
jobs:
  build:
    # pre built image from docker
    docker:
      - image: cirrusci/flutter
    steps:
      # to confirm that all is ok with the project
      - checkout
      - run:
          name: run flutter docker
          command: flutter doctor

      - run:
          name: check flutter test
          command: flutter test
      
workflow:
  name: build
  jobs:
    - build